### ISSUE TITLE
panic: interface conversion: error is *awserr.baseError, not *kv.NotFoundError

### ISSUE THREAD

**Issue by tomwilkie** [jetstack/vault-unsealer#4]
```
$ kubectl logs --namespace=kube-system vault-ip-10-76-47-170.eu-west-2.compute.internal vault-unsealer 
time="2017-11-30T15:44:44Z" level=info msg="checking if vault is sealed..." 
time="2017-11-30T15:44:44Z" level=info msg="vault sealed: true" 
panic: interface conversion: error is *awserr.baseError, not *kv.NotFoundError

goroutine 1 [running]:
github.com/jetstack/vault-unsealer/pkg/kv/aws_kms.(*awsKMS).Get(0xc4201a8b10, 0xc420017720, 0xe, 0x0, 0x0, 0x1, 0x1, 0xc420015700)
	/go/src/github.com/jetstack/vault-unsealer/pkg/kv/aws_kms/aws_kms.go:57 +0x134
github.com/jetstack/vault-unsealer/pkg/vault.(*vault).Unseal(0xc4200ff5e0, 0x10, 0xc42014bb10)
	/go/src/github.com/jetstack/vault-unsealer/pkg/vault/vault.go:83 +0xd3
github.com/jetstack/vault-unsealer/cmd.glob..func2.1(0x1063bc0, 0xc4200ff5e0)
	/go/src/github.com/jetstack/vault-unsealer/cmd/unseal.go:73 +0x125
github.com/jetstack/vault-unsealer/cmd.glob..func2(0x10a7c80, 0xc4201a8630, 0x0, 0x3)
	/go/src/github.com/jetstack/vault-unsealer/cmd/unseal.go:79 +0x256
github.com/jetstack/vault-unsealer/vendor/github.com/spf13/cobra.(*Command).execute(0x10a7c80, 0xc4201a8570, 0x3, 0x3, 0x10a7c80, 0xc4201a8570)
	/go/src/github.com/jetstack/vault-unsealer/vendor/github.com/spf13/cobra/command.go:651 +0x23d
github.com/jetstack/vault-unsealer/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x10a7a60, 0x4d8bc7, 0xc420050060, 0x10a7a00)
	/go/src/github.com/jetstack/vault-unsealer/vendor/github.com/spf13/cobra/command.go:726 +0x2fe
github.com/jetstack/vault-unsealer/vendor/github.com/spf13/cobra.(*Command).Execute(0x10a7a60, 0x4d8d0f, 0xc420050060)
	/go/src/github.com/jetstack/vault-unsealer/vendor/github.com/spf13/cobra/command.go:685 +0x2b
github.com/jetstack/vault-unsealer/cmd.Execute()
	/go/src/github.com/jetstack/vault-unsealer/cmd/root.go:51 +0x31
main.main()
	/go/src/github.com/jetstack/vault-unsealer/main.go:20 +0xa1
```

**Comment by tomwilkie** [comment]
I believe this is because I've not quite got the IAM permissions correct just yet.
